server:
  port: 8088
spring:
  application:
    name: wishlist-service
  data:
     mongodb:
        database: wallmart
        port: 27017
        host: localhost
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
eureka:
  instance:
    hostname: localhost

